"""followers

Revision ID: 025465ee8220
Revises: 9f9909bbc5e9
Create Date: 2023-08-22 23:31:49.127570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025465ee8220'
down_revision = '9f9909bbc5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
